/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Model.PatientDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author zhaojiyuan
 */
public class ManagePatientsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAccountJPanel
     */
    
    private JPanel userProcessContainer;
    private PatientDirectory patientDirectory;
    
    public ManagePatientsJPanel(JPanel userProcessContainer,PatientDirectory patientDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patientDirectory = patientDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createPatientsJButton = new javax.swing.JButton();
        viewPatientsJButton = new javax.swing.JButton();

        createPatientsJButton.setText("Create Patients");
        createPatientsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPatientsJButtonActionPerformed(evt);
            }
        });

        viewPatientsJButton.setText("View Patients");
        viewPatientsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatientsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewPatientsJButton)
                    .addComponent(createPatientsJButton))
                .addGap(346, 346, 346))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(createPatientsJButton)
                .addGap(113, 113, 113)
                .addComponent(viewPatientsJButton)
                .addContainerGap(288, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createPatientsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPatientsJButtonActionPerformed
        // TODO add your handling code here:
        CreatePatientsJPanel createPatientsJPanel = new CreatePatientsJPanel(userProcessContainer,patientDirectory);
        userProcessContainer.add("CreatePatientsJPanel",createPatientsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_createPatientsJButtonActionPerformed

    private void viewPatientsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatientsJButtonActionPerformed
        // TODO add your handling code here:
        ViewPatientsJPanel viewPatientsJPanel = new ViewPatientsJPanel(userProcessContainer,patientDirectory);
        userProcessContainer.add("ViewJPanel",viewPatientsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewPatientsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPatientsJButton;
    private javax.swing.JButton viewPatientsJButton;
    // End of variables declaration//GEN-END:variables
}
