/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Patient;
import Model.PatientDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhaojiyuan
 */
public class ViewPatientsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private JPanel userProcessContainer;
    private PatientDirectory patientDirectory;
    
    
    public ViewPatientsJPanel(JPanel userProcessContainer, PatientDirectory patientDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patientDirectory = patientDirectory;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) viewJTable.getModel();
        model.setRowCount(0);
        
        for (Patient patient : patientDirectory.getPatientDirectory()) {
            Object[] object = new Object[5];
            object[0] = patient;
            object[1] = patient.getPatientID();
            object[2] = patient.getAge();
            object[3] = patient.getPrimaryDoctorName();
            object[4] = patient.getPreferredPharmacy();
            model.addRow(object);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewJTable = new javax.swing.JTable();
        viewAndUpdateJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();
        searchJButton = new javax.swing.JButton();
        searchJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("View All Patients");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 39, -1, -1));

        viewJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Patient ID", "Age", "Primary Doctor Name", "Preferred Pharmacy"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 760, 110));

        viewAndUpdateJButton.setText("View and Update");
        viewAndUpdateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAndUpdateJButtonActionPerformed(evt);
            }
        });
        add(viewAndUpdateJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        deleteJButton.setText("Delete");
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });
        add(deleteJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        searchJButton.setText("Search using Patient ID");
        searchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJButtonActionPerformed(evt);
            }
        });
        add(searchJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));
        add(searchJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 210, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = viewJTable.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to delete !!!");
            return;
        }
        
        Patient patient = (Patient)viewJTable.getValueAt(selectedRow, 0);
        
        patientDirectory.deletePatient(patient);
        
        populateTable();
    }//GEN-LAST:event_deleteJButtonActionPerformed

    private void viewAndUpdateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAndUpdateJButtonActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = viewJTable.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to view and update !!!");
            return;
        }
        
        Patient patient = (Patient)viewJTable.getValueAt(selectedRow, 0);
        
        UpdateJPanel updateJPanel = new UpdateJPanel(userProcessContainer,patient);
        userProcessContainer.add("UpdateJPanel",updateJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_viewAndUpdateJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void searchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJButtonActionPerformed
        // TODO add your handling code here:
        String patientID = searchJTextField.getText();
        if (patientID.equals(null) || patientID.equals("")) {
            JOptionPane.showMessageDialog(null, "Please input a valid patient ID !!!");
            return;
        }
        Patient patient = patientDirectory.searchUsingPatientID(patientID);
        
        if (patient == null) {
            JOptionPane.showMessageDialog(null, "Can not find patient ID");
            return;
        }
        SearchJPanel searchJPanel = new SearchJPanel(userProcessContainer,patient);
        userProcessContainer.add("SearchJPanel",searchJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_searchJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton searchJButton;
    private javax.swing.JTextField searchJTextField;
    private javax.swing.JButton viewAndUpdateJButton;
    private javax.swing.JTable viewJTable;
    // End of variables declaration//GEN-END:variables
}
